FROM node:lts-alpine3.19
WORKDIR /user_interface/ui_project

# Copy the necessary files to the WORKDIR
COPY ./6-user_interface/ui_project/package.json .
COPY ./6-user_interface/ui_project/package-lock.json .

RUN npm i
# Install dependencies
RUN npm install
# RUN apk --no-cache add curl




# Copy the rest of the application code
COPY ./6-user_interface/start.sh /user_interface/start.sh
COPY ./6-user_interface/ui_project /user_interface/ui_project

EXPOSE 3000

CMD ["npm", "run", "dev"]

