FROM python:3.10-slim

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /monitoring
RUN pip install --upgrade pip
# COPY ./4-monitoring/report/requirements.txt /monitoring/report/requirements.txt
# COPY ./4-monitoring/report/start.sh /monitoring/report/start.sh
COPY ./4-monitoring/report/  /monitoring/report/

RUN pip install --no-cache-dir --upgrade -r report/requirements.txt
RUN chmod +x report/start.sh


# COPY ./tests /code/tests
EXPOSE 8888
EXPOSE 8000



# CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
ENTRYPOINT ["report/start.sh"]
