FROM python:3.10-slim

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /deployment
RUN pip install --upgrade pip
RUN pip install fastapi 
COPY /3-deployment/ .
RUN pip install --no-cache-dir --upgrade -r app/requirements.txt
RUN chmod +x start.sh


# COPY ./tests /code/tests
EXPOSE 8000 
ENTRYPOINT ["/deployment/start.sh"]
