name: CI

on: [push, pull_request]

jobs:
  lint & quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install ruff
        run: pip install ruff
      
      - name: Install flake8
        run: pip install flake8

      - name: Run ruff deployment
        run: ruff check 3-deployment 

      - name: Run flake8
        run: flake8 3-deployment 
      

        

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r dev.requirements.txt

      - name: Run tests
        run: pytest 3-deployment/app/api/system_monitoring
